export const SymptomsList = [
    {label: "Fatiga", value: "Fatiga"},
    {label: "Esputo", value: "Esputo"},
    {label: "Fiebre intermitente", value: "Fiebre intermitente"},
    {label: "Edema de las extremidades", value: "Edema de las extremidades"},
    {label: "Dolor de cabeza", value: "Dolor de cabeza"},
    {label: "Accidente cerebrovascular", value: "Accidente cerebrovascular"},
    {label: "Disnea (dificultad para respirar)", value: "Disnea (dificultad para respirar)"},
    {label: "Dolor de garganta", value: "Dolor de garganta"},
    {label: "Ageusia (pérdida del gusto)", value: "Ageusia (pérdida del gusto)"},
    {label: "Nueva hipertensión", value: "Nueva hipertensión"},
    {label: "Anosmia (pérdida del olfato)", value: "Anosmia (pérdida del olfato)"},
    {label: "Miocarditis", value: "Miocarditis"},
    {
        label: "Polipnea post-actividad (jadeo después del ejercicio)",
        value: "Polipnea post-actividad (jadeo después del ejercicio)"
    },
    {label: "Arritmia", value: "Arritmia"},
    {label: "Dolor en las articulaciones", value: "Dolor en las articulaciones"},
    {label: "Insuficiencia renal", value: "Insuficiencia renal"},
    {label: "Dolor abdominal", value: "Dolor abdominal"},
    {label: "Mareos", value: "Mareos"},
    {label: "Tos", value: "Tos"},
    {label: "Trastorno del sueño", value: "Trastorno del sueño"},
    {label: "Sudar", value: "Sudar"},
    {label: "Temblor", value: "Temblor"},
    {label: "Náuseas o vómitos", value: "Náuseas o vómitos"},
    {label: "Confusión", value: "Confusión"},
    {label: "Estreñimiento", value: "Estreñimiento"},
    {label: "Trastorno de atención", value: "Trastorno de atención"},
    {label: "Trastornos digestivos", value: "Trastornos digestivos"},
    {label: "Pérdida de memoria", value: "Pérdida de memoria"},
    {label: "Pérdida de peso", value: "Pérdida de peso"},
    {label: "Pérdida de audición o tinnitus", value: "Pérdida de audición o tinnitus"},
    {label: "Alopecia", value: "Alopecia"},
    {label: "Ansiedad", value: "Ansiedad"},
    {label: "Signos cutáneos", value: "Signos cutáneos"},
    {label: "Depresión", value: "Depresión"},
    {label: "Aumento de la frecuencia cardíaca en reposo", value: "Aumento de la frecuencia cardíaca en reposo"},
    {label: "Problemas de salud mental", value: "Problemas de salud mental"},
    {label: "Palpitaciones", value: "Palpitaciones"},
    {label: "Enfermedad psiquiátrica", value: "Enfermedad psiquiátrica"},
    {label: "Molestias en el pecho", value: "Molestias en el pecho"},
    {label: "Trastornos del estado de ánimo", value: "Trastornos del estado de ánimo"},
    {label: "Reducción de la capacidad pulmonar", value: "Reducción de la capacidad pulmonar"},
    {label: "Escalofríos", value: "Escalofríos"},
    {label: "Apnea del sueño", value: "Apnea del sueño"},
    {label: "Ojos rojos", value: "Ojos rojos"},
    {label: "Trastorno de estrés postraumático (TEPT)", value: "Trastorno de estrés postraumático (TEPT)"},
    {label: "Paranoia", value: "Paranoia"},
    {label: "Fibrosis Pulmonar", value: "Fibrosis Pulmonar"},
    {label: "Trastorno obsesivo-compulsivo (TOC)", value: "Trastorno obsesivo-compulsivo (TOC)"},
    {label: "Lavado intermitente", value: "Lavado intermitente"},
    {label: "Diabetes mellitus", value: "Diabetes mellitus"}
]
